name: Auto assign issues and PRs to project

on:
  issues:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_project:
    runs-on: ubuntu-latest
    name: Auto assign issues and PRs to project
    steps:
    - name: Assign new issues to project into triage column
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: 'https://github.com/wduda/TravelWindowII/projects/1'
        column_name: 'Triage'