# This workflow will create the release artifact and a release on GitHub
name: release

on:
  # on push of new release tag to master
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  # also allows job to be run manually from actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version'
  
jobs:
  build_artefact:
    runs-on: ubuntu-latest

    steps:
      # checks out master under $GITHUB_WORKSPACE
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: '${{ github.event.inputs.tag }}'

      # create a zip as a release archive
      - name: create release archive
        uses: thedoctor0/zip-release@master
        with:
          filename: 'TravelWindowII-${{ github.event.inputs.tag }}.zip'
          exclusions: '*.git* .github* *.vscode* *.gitignore*'