# This workflow will create the release artifact and a release on GitHub
name: GitHub release

on:
  # allows job to be run manually from actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version'
  
jobs:
  build_artefact:
    runs-on: ubuntu-latest

    steps:
      # checks out main into $GITHUB_WORKSPACE
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.inputs.tag }}'
          path: 'TravelWindowII'

      # create a zip as a release archive
      - name: create release archive
        uses: thedoctor0/zip-release@master
        with:
          filename: 'TravelWindowII-${{ github.event.inputs.tag }}.zip'
          exclusions: '*.git* *.github* *.vscode* *.gitignore* /*doc/* /*screenshots/*'

      # create the GitHub release
      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: ${{ github.event.inputs.tag }}
          files: 'TravelWindowII-${{ github.event.inputs.tag }}.zip'